// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9U5y1F3CsCzqrJgvQWjpAFMejnKMTrm8',
    appId: '1:73932782693:web:865834219355e3f73d1a8c',
    messagingSenderId: '73932782693',
    projectId: 'gantek-e6fbc',
    authDomain: 'gantek-e6fbc.firebaseapp.com',
    storageBucket: 'gantek-e6fbc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNQoJJoSla6dedef45tMfd58RM1nRwglw',
    appId: '1:73932782693:android:d6c7e27f496d53153d1a8c',
    messagingSenderId: '73932782693',
    projectId: 'gantek-e6fbc',
    storageBucket: 'gantek-e6fbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiyaL-NvmD9OMXOoYnbCq2A2sgPTAfqyQ',
    appId: '1:73932782693:ios:9701b0f42a448f413d1a8c',
    messagingSenderId: '73932782693',
    projectId: 'gantek-e6fbc',
    storageBucket: 'gantek-e6fbc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiyaL-NvmD9OMXOoYnbCq2A2sgPTAfqyQ',
    appId: '1:73932782693:ios:9701b0f42a448f413d1a8c',
    messagingSenderId: '73932782693',
    projectId: 'gantek-e6fbc',
    storageBucket: 'gantek-e6fbc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9U5y1F3CsCzqrJgvQWjpAFMejnKMTrm8',
    appId: '1:73932782693:web:e6e0987809acc5363d1a8c',
    messagingSenderId: '73932782693',
    projectId: 'gantek-e6fbc',
    authDomain: 'gantek-e6fbc.firebaseapp.com',
    storageBucket: 'gantek-e6fbc.firebasestorage.app',
  );
}
